namespace FitLife.Core.Models;

/// <summary>
/// Represents a precomputed recommendation for a user
/// Generated by background worker every 10 minutes
/// </summary>
public class Recommendation
{
    /// <summary>
    /// Composite primary key: UserId + ItemId
    /// </summary>
    public string UserId { get; set; } = string.Empty;
    
    public string ItemId { get; set; } = string.Empty;
    
    /// <summary>
    /// Type of item being recommended: Class, Instructor, etc.
    /// </summary>
    public string ItemType { get; set; } = "Class";
    
    /// <summary>
    /// Computed recommendation score (higher = better match)
    /// Based on 9-factor algorithm in ScoringEngine
    /// </summary>
    public decimal Score { get; set; }
    
    /// <summary>
    /// Rank in user's recommendation list (1 = top recommendation)
    /// </summary>
    public int Rank { get; set; }
    
    /// <summary>
    /// Human-readable explanation: "Based on your love for Yoga and instructor preference"
    /// </summary>
    public string Reason { get; set; } = string.Empty;
    
    /// <summary>
    /// Timestamp when this recommendation was generated
    /// Used for cache invalidation (10 minute TTL)
    /// </summary>
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;
    
    // Navigation properties
    public virtual User? User { get; set; }
    public virtual Class? Class { get; set; }
}
